import { WordCloudResType } from '../../../types/companies';

export const wordCloudSampleData: WordCloudResType[] = [
  {
    success: true,
    results: [
      { word: 'Reviews', score: 600 },
      { word: 'Proxy', score: 200 },
      { word: 'Jet', score: 50 },
      { word: 'Carscom', score: 60 },
      { word: 'WeddingWire', score: 70 },
      { word: 'Softwareadvice', score: 150 },
      { word: 'DealerRater', score: 100 },
      { word: 'AppStore', score: 300 },
      { word: 'Zomato', score: 100 },
      { word: 'Business', score: 400 },
      { word: 'Hotelscom', score: 150 },
      { word: 'Intelligent', score: 500 },
      { word: 'Trulia', score: 125 },
      { word: 'Zocdoc', score: 50 },
      { word: 'Bookingcom', score: 40 },
      { word: 'Homestars', score: 30 },
      { word: 'GooglePlay', score: 350 },
      { word: 'Tripadvisor', score: 300 },
      { word: 'Management', score: 400 },
      { word: 'Flipkart', score: 80 },
      { word: 'CustomerLobby', score: 90 },
      { word: 'Amazon', score: 100 },
      { word: 'Etsy', score: 75 },
      { word: 'Foursquare', score: 80 },
      { word: 'Indeed', score: 70 },
      { word: 'API', score: 180 },
      { word: 'AirBnb', score: 400 },
      { word: 'CreditKarma', score: 100 },
      { word: 'Headless', score: 300 },
      { word: 'Data', score: 350 },
      { word: 'BBB', score: 100 },
      { word: 'Capterra', score: 100 },
      { word: 'Yelp', score: 100 },
      { word: 'Website', score: 200 },
      { word: 'McDonald’s', score: 100 },
      { word: 'Ebay', score: 100 },
      { word: 'Glassdoor', score: 100 },
      { word: 'Google', score: 300 },
      { word: 'TrustedShops', score: 20 },
      { word: 'GearBest', score: 60 },
      { word: 'Steam', score: 70 },
      { word: 'AliExpress', score: 80 },
      { word: 'Talabat', score: 90 },
      { word: 'Martindale', score: 100 },
      { word: 'Captcha', score: 100 },
      { word: 'RottenTomatoes', score: 100 },
      { word: 'Index', score: 100 },
      { word: 'IMDb', score: 100 },
      { word: 'ProductHunt', score: 100 },
      { word: 'OpenRice', score: 100 },
      { word: 'Expedia', score: 100 },
      { word: 'Rating', score: 100 },
      { word: 'JSON', score: 100 },
      { word: 'Avvo', score: 100 },
      { word: 'G2', score: 100 },
      // { word: 'Trustpilot', score: 100 },
      { word: 'Thumbstack', score: 100 },
      { word: 'NAP', score: 100 },
      { word: 'HungerStation', score: 100 },
      { word: 'Zillow', score: 100 },
      { word: 'Yell', score: 100 },
      { word: 'Facebook', score: 100 },
      { word: 'SiteJabber', score: 100 },
      { word: 'YellowPages', score: 100 },
      { word: 'TheKnot', score: 100 },
      { word: 'Agoda', score: 100 },
      { word: 'Healthgrades', score: 100 },
      { word: 'Trustradius', score: 50 },
      { word: 'OpenTable', score: 120 },
      { word: 'Scraper', score: 60 },
      { word: 'Newegg', score: 50 },
      { word: 'Lawyers', score: 40 },
      { word: 'Clutch', score: 20 },
      { word: 'Vitals', score: 30 },
      { word: 'Datashake', score: 100 },
      { word: 'HTML', score: 100 },
    ],
  },
];
